next: update first app guidance aligned with YODAV8 API
Rokid/yoda-book pull request #10
Opened 2019-08-02 05:53 UTC by legendecas

2019-08-02 06:10 UTC, yorkie commented on zh-cn/guidance/01-build-your-first-app.md
> +[YodaOS 开发者工具](https://github.com/yodaos-project/yoda-platform-tools) 提供了一系列的便捷工具来对 YodaOS 设备进行操作，如发送文本指令，发送 NLP 意图，启动、安装应用等。
应该没有 NLP 意图了吧？

2019-08-02 06:12 UTC, yorkie commented on zh-cn/guidance/01-build-your-first-app.md
> +可以从 [YodaOS 开发者工具 Releases](https://github.com/yodaos-project/yoda-platform-tools/releases) 页面下载 YodaOS 开发者工具。
是不是可以把 YodaOS 开发者工具定义成"YPT"作为简称，感觉这个称谓有点冗长～

2019-08-02 06:13 UTC, yorkie commented on zh-cn/guidance/01-build-your-first-app.md
> +在创建 `Application` 的时候，`Application` 接收一个字面对象，这个对象上可以挂载多个事件的监听函数，通过这些监听函数我们可以监听应用与系统的事件：
这里的字面对象能否链接一个 JS 的说明，要不然其他对 JS 不熟悉的开发者可能不知道。

2019-08-02 06:14 UTC, yorkie commented on zh-cn/guidance/01-build-your-first-app.md
> +在创建 `Application` 的时候，`Application` 接收一个字面对象，这个对象上可以挂载多个事件的监听函数，通过这些监听函数我们可以监听应用与系统的事件：
```suggestion
在创建 `Application` 的时候，`Application` 接收一个字面对象，这个对象上可以挂载多个事件的监听函数，通过这些监听函数可以监听应用与系统事件：
```

2019-08-02 06:18 UTC, yorkie requested changes
Great works @legendecas :)

2019-08-02 06:18 UTC, yorkie commented on zh-cn/guidance/01-build-your-first-app.md
>      ]
感觉这个章节缺乏对这些字段的说明。

2019-08-02 06:18 UTC, yorkie commented on zh-cn/guidance/01-build-your-first-app.md
> +package.json 类似于 [npm](https://www.npmjs.com/) 包，但是对于 YodaOS 应用来说，其中最重要的字段莫过于 name 与 manifest：前者声明了应用的本地 ID，后者声明了需要向 YodaRuntime 申请的权限等信息。
```suggestion
package.json 类似于 [npm](https://www.npmjs.com/) 包，但是对于 YodaOS 应用来说，其中最重要的字段莫过于 name 与 manifest：前者声明了应用的本地 ID，后者声明了需要向系统申请的权限等信息。
```

2019-08-02 06:18 UTC, yorkie commented on zh-cn/guidance/01-build-your-first-app.md
>  应用可以通过 URL 的形式唤起其它应用，并将当前的交互托付给能处理这个 URL 的应用。
这里是不是可以提一下我们是怎么通过 Url 处理 NLP 的？

2019-08-05 08:29 UTC, LanFly commented on zh-cn/guidance/01-build-your-first-app.md
> +对于 YodaOS 来说，每个应用都是一个 [CommonJS](https://nodejs.org/docs/latest/api/modules.html) 模块。YodaOS 的应用的主入口即为通过 `require('@yodaos/application').Application` 创建的 Application 模块。
> `require('@yodaos/application').Application` 创建的 Application 模块

这里 `模块` 改为 `实例` 会更好吧？

2019-08-07 07:12 UTC, legendecas commented on zh-cn/guidance/01-build-your-first-app.md
>      ]
是的，但是紧跟着就会链接到具体的 manifest 文档，所以这个章节不再赘述。

2019-08-08 06:08 UTC, LanFly approved these changes

2019-08-08 08:33 UTC, yorkie approved these changes

2019-08-08 08:37 UTC, merged