language: support multi language
Rokid/yoda-book pull request #5
Opened 2019-01-03 12:06 UTC by lolBig

- adjust the document structure, support multi language
- add English version

2019-01-03 13:33 UTC, yorkie requested changes
Too much errors, please fix them firstly

2019-01-03 13:33 UTC, yorkie commented on LANGS.md
> +* [中文](zh-hans/)
Corrections: 1) 中文 > 简体中文 2) zh-hans > zh-CN

2019-01-03 13:33 UTC, yorkie commented on README.md
> +[Apache 2.0][]
Please remove this line.

2019-01-03 13:33 UTC, yorkie commented on book.json
> +}
EOF

2019-01-03 13:33 UTC, yorkie commented on en/best-practice/01-testing.md
> +# tools/runtime-install
Replace the # > $

2019-01-03 13:33 UTC, yorkie commented on en/best-practice/01-testing.md
> +# tools/runtime-op --vuid restart
Ditto

2019-01-03 13:33 UTC, yorkie commented on en/best-practice/01-testing.md
> +For example: Ruo Qi, I want to listen to children's songs.
I think "Ruo Qi" should still be in Chinese, or in pinyin with tones.

2019-01-03 13:33 UTC, yorkie commented on en/best-practice/01-testing.md
> +      runtime.openUrl('url', {form: 'cut'})
The above lines crash the program :(

2019-01-03 13:33 UTC, yorkie commented on en/best-practice/01-testing.md
> +# tools/mock --asr 'change one'
Ditto, use $ instead of #.

2019-01-03 13:33 UTC, yorkie commented on en/best-practice/03-performance-stability.md
> +## Start Up
Should be "bootstrap"

2019-01-03 13:33 UTC, yorkie commented on en/best-practice/03-performance-stability.md
> +As mentioned earlier, [ShadowNode][] uses an event-driven, non-blocking I/O model. This model is implemented via [libtuv][]. If the application logic contains I/O or other blocking tasks, the develop
"the developer can Put the task" -> The Put should be in lower case :)

2019-01-03 13:33 UTC, yorkie commented on en/best-practice/03-performance-stability.md
> +As mentioned earlier, [ShadowNode][] uses an event-driven, non-blocking I/O model. This model is implemented via [libtuv][]. If the application logic contains I/O or other blocking tasks, the develop
And the link is wrong.

2019-01-03 13:33 UTC, yorkie commented on en/best-practice/03-performance-stability.md
> +- For a large number of intensive calculations, you can use the tools provided by the system such as `simpleperf` to view the application function call for a period of time (requires unstriped librar
1. flame map -> flamegraph

2019-01-03 13:33 UTC, yorkie commented on en/best-practice/03-performance-stability.md
> +  Napi_value functionExportToJS(napi_env env, napi_callback_info info) {
The `Napi_value` should be `napi_value`

2019-01-03 13:33 UTC, yorkie commented on en/best-practice/03-performance-stability.md
> +- Multi-threaded callback is not enabled [Handle Scope](https://nodejs.org/docs/latest/api/n-api.html#n_api_napi_open_handle_scope)
Not enabled -> disabled.

2019-01-03 13:33 UTC, yorkie commented on en/guidance/01-build-your-first-app.md
> +[YODAOS Developer Tools](https://github.com/yodaos-project/yoda-platform-tools) provides a range of convenient tools for manipulating YODAOS devices, such as sending text commands, sending NLP intent
Install > installing

2019-01-03 13:33 UTC, yorkie commented
And we need a directory: `locals` and put different versions inside there.

2019-01-04 09:39 UTC, yorkie commented on en/yodaos-source/customization/03-light.md
> + Static struct hw_module_methods_t led_module_methods = {
Static -> static

2019-01-04 09:39 UTC, yorkie commented on en/yodaos-source/customization/03-light.md
> + Struct hw_module_t HAL_MODULE_INFO_SYM = {
Ditto

2019-01-18 09:58 UTC, guoguo0416 commented on en/yodaos-source/customization/03-light.md
> + Struct hw_module_t HAL_MODULE_INFO_SYM = {
```suggestion
 struct hw_module_t HAL_MODULE_INFO_SYM = {
```

2019-01-18 11:00 UTC, guoguo0416 commented on en/guidance/01-build-your-first-app.md
> +The `activity` provided by the system framework is an object that conforms to Node.js [EventEmitter API](https://nodejs.org/docs/latest/api/events.html#events_events), on which we can listen to any a
'activity' that main function param should provide all supported api list

2019-01-18 11:11 UTC, guoguo0416 commented on en/best-practice/03-performance-stability.md
> +## Start Up
this file 'Official Implementation' link do not work, and there are more one place using it 
plz fix it

2019-01-18 11:14 UTC, guoguo0416 commented on en/yodaos-source/system/compile-run.md
> +* Refer to Chapter 6 of the Rokid Kamino18 Universal Install Guide V2.5.pdf for a brief description.
using 'Refer to ...' should add link to the reference page
plz fix it

2019-01-18 11:17 UTC, guoguo0416 commented on zh-hans/yodaos-source/system/compile-run.md
>  #### OpenWrt 目录结构
this file 'please refer to [API chapter]...' link do not work, actually result is page 404
plz fix it

2019-01-22 11:28 UTC, algebrait approved these changes

2019-01-22 11:54 UTC, merged